# Generated by Django 5.2.4 on 2025-07-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_alter_reuniao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.membro'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.reuniao'),
        ),
    ]
