# Generated by Django 5.2.4 on 2025-07-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('lider', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Célula',
                'verbose_name_plural': 'Células',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_conversao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('celula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='membros.celula')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reuniao', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('celula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes', to='membros.celula')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-data_reuniao', 'celula__nome'],
                'unique_together': {('celula', 'data_reuniao')},
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias_registradas', to='membros.membro')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='membros.reuniao')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'ordering': ['reuniao__data_reuniao', 'membro__nome_completo'],
                'unique_together': {('reuniao', 'membro')},
            },
        ),
    ]
