# Generated by Django 5.2.4 on 2025-07-25 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celula',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='data_conversao',
        ),
        migrations.AddField(
            model_name='celula',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='data_adesao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='membro',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='celula',
            name='lider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='membros.membro'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='data_reuniao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
