# Generated by Django 5.2.4 on 2025-07-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0002_remove_celula_endereco_remove_membro_data_conversao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reuniao',
            options={'ordering': ['-data_reuniao'], 'verbose_name': 'Reunião', 'verbose_name_plural': 'Reuniões'},
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='data_registro',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='email',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='reuniao',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='membro',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tema',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='celula',
            name='lider',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='nome_completo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
