# Generated by Django 5.2.4 on 2025-07-29 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_frequencia_observacao_alter_frequencia_membro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencia',
            options={'ordering': ['reuniao__data_reuniao', 'reuniao__hora_reuniao', 'membro__nome_completo'], 'verbose_name': 'Frequência', 'verbose_name_plural': 'Frequências'},
        ),
        migrations.AlterModelOptions(
            name='reuniao',
            options={'ordering': ['-data_reuniao', '-hora_reuniao'], 'verbose_name': 'Reunião', 'verbose_name_plural': 'Reuniões'},
        ),
        migrations.AlterUniqueTogether(
            name='reuniao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='data_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='hora_reuniao',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterUniqueTogether(
            name='reuniao',
            unique_together={('celula', 'data_reuniao', 'hora_reuniao')},
        ),
    ]
