# Generated by Django 5.2.4 on 2025-08-01 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0005_alter_frequencia_options_alter_reuniao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencia',
            options={'ordering': ['reuniao__data_reuniao', 'membro__nome_completo'], 'verbose_name': 'Frequência', 'verbose_name_plural': 'Frequências'},
        ),
        migrations.RenameField(
            model_name='membro',
            old_name='observacoes',
            new_name='observacao',
        ),
        migrations.AlterUniqueTogether(
            name='reuniao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='data_registro',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='sexo',
        ),
        migrations.AddField(
            model_name='membro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencia', to='membros.membro'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencia', to='membros.reuniao'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_adesao',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_nascimento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='nome_completo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='data_reuniao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='hora_reuniao',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='tema',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
