# Generated by Django 5.2.4 on 2025-12-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0005_alter_frequencia_options_alter_reuniao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celula',
            name='lider',
        ),
    ]
